name: Greenhouse Log
options:
  bundleIdPrefix: com.shimondeitel.greenhouselog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  GreenhouseLog:
    type: application
    platform: iOS
    sources:
      - path: GreenhouseLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.greenhouselog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: GreenhouseLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  GreenhouseLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GreenhouseLogTests
      - path: GreenhouseLog.storekit
    dependencies:
      - target: GreenhouseLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.greenhouselog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  GreenhouseLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: GreenhouseLogUITests
    dependencies:
      - target: GreenhouseLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.greenhouselog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  GreenhouseLog:
    build:
      targets:
        GreenhouseLog: all
        GreenhouseLogTests: [test]
        GreenhouseLogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: GreenhouseLog.storekit
    test:
      config: Debug
      storeKitConfiguration: GreenhouseLog.storekit
      targets:
        - GreenhouseLogTests
        - GreenhouseLogUITests
    archive:
      config: Release
